name: My Workflow
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync ArgoCD Application
        uses: omegion/argocd-app-actions@master
        with:
          address: "localhost" #ArgoCD server address. Also try - "localhost:443" or just "localhost"
          token: ${{ secrets.ARGOCD_TOKEN }} # ArgoCD Token.
          appName: "myapp-argo-application" # Application name to sync.
